package ansi378

import "encoding/base64"

var (
	invalidShortFMD = []byte{10, 11, 12, 13}
	// two byte FMD
	valid2ByteFMDBase64 = "Rk1SACAyMAABLgAz/v8AAAFlAYgAxQDFAQAAAFYtQFABI3hkgH8BWHZhgFUBQnZgQEoAx3FggJIBLRpfgPwA3k1cQHYBPR1cQEsBTRxcQGAA2BdagO0A2KxaQLABDgpaQG8AkG5ZQK8AuGpZgQUBLZ5ZgMwBBmVYgPgBWJhYQM0AmwRXgMEASWVXQNYAcgVVgHQBE3lUgNEBLaBUQPkAQmBTQDYAlWlTgMABIQRTgJcBRhdTQHoAohBSgKMATwtQgK0BVwVOQKQAhQ9OgJ0BVBdNgFMAgRRLgSYAl01KgDcAdGxGQMYA9QJEQMsBYaBBgB0AoA8+gSYAj6c9QN0AHAg6gBoA+HQ6QBoAsmg3gRQAN7M2ALQBaggxAOcBbTcxAOUBXUErAMsBbU0qAAA="
	valid2ByteFMD, _    = base64.StdEncoding.DecodeString(valid2ByteFMDBase64)

	// six byte FMD
	//TODO: get an actual different FMD; this is the same as the two-byte and results in coverage loss
	valid6ByteFMDBase64 = "Rk1SACAyMAABLgAz/v8AAAFlAYgAxQDFAQAAAFYtQFABI3hkgH8BWHZhgFUBQnZgQEoAx3FggJIBLRpfgPwA3k1cQHYBPR1cQEsBTRxcQGAA2BdagO0A2KxaQLABDgpaQG8AkG5ZQK8AuGpZgQUBLZ5ZgMwBBmVYgPgBWJhYQM0AmwRXgMEASWVXQNYAcgVVgHQBE3lUgNEBLaBUQPkAQmBTQDYAlWlTgMABIQRTgJcBRhdTQHoAohBSgKMATwtQgK0BVwVOQKQAhQ9OgJ0BVBdNgFMAgRRLgSYAl01KgDcAdGxGQMYA9QJEQMsBYaBBgB0AoA8+gSYAj6c9QN0AHAg6gBoA+HQ6QBoAsmg3gRQAN7M2ALQBaggxAOcBbTcxAOUBXUErAMsBbU0qAAA="
	valid6ByteFMD, _    = base64.StdEncoding.DecodeString(valid6ByteFMDBase64)

	// our valid record used to create the two and six byte FMDs above
	validHeader = RecordHeader{
		CBEFFOwner:          51,
		CBEFFType:           65279,
		EquipmentCompliance: 0,
		EquipmentID:         0,
		FormatIdentifier:    "FMR",
		ImageResolutionX:    197,
		ImageResolutionY:    197,
		ImageSizeX:          357,
		ImageSizeY:          392,
		RecordLength:        302,
		Reserved:            0,
		VersionNumber:       " 20", // the space is important? I guess?
		Views:               1,
	}

	valid2ByteViewRecords = &[]ViewRecord{
		ViewRecord{
			FingerPosition: 0,
			ViewNumber:     0,
			ImpressionType: 0,
			FingerQuality:  86,
			MinutiaeCount:  45,
			Minutiaes: []Minutiae{
				Minutiae{
					MinutiaeType: 1,
					CoordinateX:  80,
					CoordinateY:  291,
					Reserved:     0,
					Angle:        120,
					Quality:      100,
				},
				Minutiae{
					MinutiaeType: 2,
					CoordinateX:  127,
					CoordinateY:  344,
					Reserved:     0,
					Angle:        118,
					Quality:      97,
				},
				Minutiae{
					MinutiaeType: 2,
					CoordinateX:  85,
					CoordinateY:  322,
					Reserved:     0,
					Angle:        118,
					Quality:      96,
				},
				Minutiae{
					MinutiaeType: 1,
					CoordinateX:  74,
					CoordinateY:  199,
					Reserved:     0,
					Angle:        113,
					Quality:      96,
				},
				Minutiae{
					MinutiaeType: 2,
					CoordinateX:  146,
					CoordinateY:  301,
					Reserved:     0,
					Angle:        26,
					Quality:      95,
				},
				Minutiae{
					MinutiaeType: 2,
					CoordinateX:  252,
					CoordinateY:  222,
					Reserved:     0,
					Angle:        77,
					Quality:      92,
				},
				Minutiae{
					MinutiaeType: 1,
					CoordinateX:  118,
					CoordinateY:  317,
					Reserved:     0,
					Angle:        29,
					Quality:      92,
				},
				Minutiae{
					MinutiaeType: 1,
					CoordinateX:  75,
					CoordinateY:  333,
					Reserved:     0,
					Angle:        28,
					Quality:      92,
				},
				Minutiae{
					MinutiaeType: 1,
					CoordinateX:  96,
					CoordinateY:  216,
					Reserved:     0,
					Angle:        23,
					Quality:      90,
				},
				Minutiae{
					MinutiaeType: 2,
					CoordinateX:  237,
					CoordinateY:  216,
					Reserved:     0,
					Angle:        172,
					Quality:      90,
				},
				Minutiae{
					MinutiaeType: 1,
					CoordinateX:  176,
					CoordinateY:  270,
					Reserved:     0,
					Angle:        10,
					Quality:      90,
				},
				Minutiae{
					MinutiaeType: 1,
					CoordinateX:  111,
					CoordinateY:  144,
					Reserved:     0,
					Angle:        110,
					Quality:      89,
				},
				Minutiae{
					MinutiaeType: 1,
					CoordinateX:  175,
					CoordinateY:  184,
					Reserved:     0,
					Angle:        106,
					Quality:      89,
				},
				Minutiae{
					MinutiaeType: 2,
					CoordinateX:  261,
					CoordinateY:  301,
					Reserved:     0,
					Angle:        158,
					Quality:      89,
				},
				Minutiae{
					MinutiaeType: 2,
					CoordinateX:  204,
					CoordinateY:  262,
					Reserved:     0,
					Angle:        101,
					Quality:      88,
				},
				Minutiae{
					MinutiaeType: 2,
					CoordinateX:  248,
					CoordinateY:  344,
					Reserved:     0,
					Angle:        152,
					Quality:      88,
				},
				Minutiae{
					MinutiaeType: 1,
					CoordinateX:  205,
					CoordinateY:  155,
					Reserved:     0,
					Angle:        4,
					Quality:      87,
				},
				Minutiae{
					MinutiaeType: 2,
					CoordinateX:  193,
					CoordinateY:  73,
					Reserved:     0,
					Angle:        101,
					Quality:      87,
				},
				Minutiae{
					MinutiaeType: 1,
					CoordinateX:  214,
					CoordinateY:  114,
					Reserved:     0,
					Angle:        5,
					Quality:      85,
				},
				Minutiae{
					MinutiaeType: 2,
					CoordinateX:  116,
					CoordinateY:  275,
					Reserved:     0,
					Angle:        121,
					Quality:      84,
				},
				Minutiae{
					MinutiaeType: 2,
					CoordinateX:  209,
					CoordinateY:  301,
					Reserved:     0,
					Angle:        160,
					Quality:      84,
				},
				Minutiae{
					MinutiaeType: 1,
					CoordinateX:  249,
					CoordinateY:  66,
					Reserved:     0,
					Angle:        96,
					Quality:      83,
				},
				Minutiae{
					MinutiaeType: 1,
					CoordinateX:  54,
					CoordinateY:  149,
					Reserved:     0,
					Angle:        105,
					Quality:      83,
				},
				Minutiae{
					MinutiaeType: 2,
					CoordinateX:  192,
					CoordinateY:  289,
					Reserved:     0,
					Angle:        4,
					Quality:      83,
				},
				Minutiae{
					MinutiaeType: 2,
					CoordinateX:  151,
					CoordinateY:  326,
					Reserved:     0,
					Angle:        23,
					Quality:      83,
				},
				Minutiae{
					MinutiaeType: 1,
					CoordinateX:  122,
					CoordinateY:  162,
					Reserved:     0,
					Angle:        16,
					Quality:      82,
				},
				Minutiae{
					MinutiaeType: 2,
					CoordinateX:  163,
					CoordinateY:  79,
					Reserved:     0,
					Angle:        11,
					Quality:      80,
				},
				Minutiae{
					MinutiaeType: 2,
					CoordinateX:  173,
					CoordinateY:  343,
					Reserved:     0,
					Angle:        5,
					Quality:      78,
				},
				Minutiae{
					MinutiaeType: 1,
					CoordinateX:  164,
					CoordinateY:  133,
					Reserved:     0,
					Angle:        15,
					Quality:      78,
				},
				Minutiae{
					MinutiaeType: 2,
					CoordinateX:  157,
					CoordinateY:  340,
					Reserved:     0,
					Angle:        23,
					Quality:      77,
				},
				Minutiae{
					MinutiaeType: 2,
					CoordinateX:  83,
					CoordinateY:  129,
					Reserved:     0,
					Angle:        20,
					Quality:      75,
				},
				Minutiae{
					MinutiaeType: 2,
					CoordinateX:  294,
					CoordinateY:  151,
					Reserved:     0,
					Angle:        77,
					Quality:      74,
				},
				Minutiae{
					MinutiaeType: 2,
					CoordinateX:  55,
					CoordinateY:  116,
					Reserved:     0,
					Angle:        108,
					Quality:      70,
				},
				Minutiae{
					MinutiaeType: 1,
					CoordinateX:  198,
					CoordinateY:  245,
					Reserved:     0,
					Angle:        2,
					Quality:      68,
				},
				Minutiae{
					MinutiaeType: 1,
					CoordinateX:  203,
					CoordinateY:  353,
					Reserved:     0,
					Angle:        160,
					Quality:      65,
				},
				Minutiae{
					MinutiaeType: 2,
					CoordinateX:  29,
					CoordinateY:  160,
					Reserved:     0,
					Angle:        15,
					Quality:      62,
				},
				Minutiae{
					MinutiaeType: 2,
					CoordinateX:  294,
					CoordinateY:  143,
					Reserved:     0,
					Angle:        167,
					Quality:      61,
				},
				Minutiae{
					MinutiaeType: 1,
					CoordinateX:  221,
					CoordinateY:  28,
					Reserved:     0,
					Angle:        8,
					Quality:      58,
				},
				Minutiae{
					MinutiaeType: 2,
					CoordinateX:  26,
					CoordinateY:  248,
					Reserved:     0,
					Angle:        116,
					Quality:      58,
				},
				Minutiae{
					MinutiaeType: 1,
					CoordinateX:  26,
					CoordinateY:  178,
					Reserved:     0,
					Angle:        104,
					Quality:      55,
				},
				Minutiae{
					MinutiaeType: 2,
					CoordinateX:  276,
					CoordinateY:  55,
					Reserved:     0,
					Angle:        179,
					Quality:      54,
				},
				Minutiae{
					MinutiaeType: 0,
					CoordinateX:  180,
					CoordinateY:  362,
					Reserved:     0,
					Angle:        8,
					Quality:      49,
				},
				Minutiae{
					MinutiaeType: 0,
					CoordinateX:  231,
					CoordinateY:  365,
					Reserved:     0,
					Angle:        55,
					Quality:      49,
				},
				Minutiae{
					MinutiaeType: 0,
					CoordinateX:  229,
					CoordinateY:  349,
					Reserved:     0,
					Angle:        65,
					Quality:      43,
				},
				Minutiae{
					MinutiaeType: 0,
					CoordinateX:  203,
					CoordinateY:  365,
					Reserved:     0,
					Angle:        77,
					Quality:      42,
				},
			},
		},
	}
)
